3: |
  build: '.'
  image: iroha2:dev
  volumes: |-
    - './configs/peer:/config'
    - './:/root/soramitsu/iroha'
  environment:
    TORII_P2P_ADDR: iroha3:1337
    TORII_API_URL: iroha3:8080
    TORII_TELEMETRY_URL: iroha3:8180
    IROHA_PUBLIC_KEY: EMPTY
    IROHA_PRIVATE_KEY: EMPTY
    SUMERAGI_TRUSTED_PEERS: EMPTY
  ports: |-
    - "1337:1337"
    - "8080:8080"
    - "8180:8180"
  init: true
  command: iroha --submit-genesis
1: |
  build: '.'
  image: iroha2:dev
  volumes: |-
    - './configs/peer:/config'
    - './:/root/soramitsu/iroha'
  environment:
    TORII_P2P_ADDR: iroha1:1337
    TORII_API_URL: iroha1:8080
    TORII_TELEMETRY_URL: iroha1:8180
    IROHA_PUBLIC_KEY: EMPTY
    IROHA_PRIVATE_KEY: EMPTY
    SUMERAGI_TRUSTED_PEERS: EMPTY
  ports: |-
    - "1337:1337"
    - "8080:8080"
    - "8180:8180"
  init: true
  command: iroha --submit-genesis
0: |
  build: '.'
  image: iroha2:dev
  volumes: |-
    - './configs/peer:/config'
    - './:/root/soramitsu/iroha'
  environment:
    TORII_P2P_ADDR: iroha0:1337
    TORII_API_URL: iroha0:8080
    TORII_TELEMETRY_URL: iroha0:8180
    IROHA_PUBLIC_KEY: EMPTY
    IROHA_PRIVATE_KEY: EMPTY
    SUMERAGI_TRUSTED_PEERS: EMPTY
  ports: |-
    - "1337:1337"
    - "8080:8080"
    - "8180:8180"
  init: true
  command: iroha --submit-genesis
2: |
  build: '.'
  image: iroha2:dev
  volumes: |-
    - './configs/peer:/config'
    - './:/root/soramitsu/iroha'
  environment:
    TORII_P2P_ADDR: iroha2:1337
    TORII_API_URL: iroha2:8080
    TORII_TELEMETRY_URL: iroha2:8180
    IROHA_PUBLIC_KEY: EMPTY
    IROHA_PRIVATE_KEY: EMPTY
    SUMERAGI_TRUSTED_PEERS: EMPTY
  ports: |-
    - "1337:1337"
    - "8080:8080"
    - "8180:8180"
  init: true
  command: iroha --submit-genesis
ha --submit-genesis
